<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\PermissionRegistrar;

use App\Models\User;
use App\Models\Customer;
use App\Models\Lead;
use App\Models\Task;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Permission cache
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        // Roles + permissions
        $this->call(RolePermissionSeeder::class);

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        // ---------- Users ----------
        $admin = User::updateOrCreate(
            ['email' => 'izadyaramirreza0@gmail.com'],
            [
                'name' => 'Admin User',
                'password' => Hash::make('Admin@123456'),
                'email_verified_at' => now(),
            ]
        );
        $admin->syncRoles(['admin']);

        $sales = User::updateOrCreate(
            ['email' => 'sales@example.com'],
            [
                'name' => 'Sales User',
                'password' => Hash::make('Sales@123456'),
                'email_verified_at' => now(),
            ]
        );
        $sales->syncRoles(['sales']);

        $sales2 = User::updateOrCreate(
            ['email' => 'sales2@example.com'],
            [
                'name' => 'Sales Demo 2',
                'password' => Hash::make('Sales@123456'),
                'email_verified_at' => now(),
            ]
        );
        $sales2->syncRoles(['sales']);

        $sales3 = User::updateOrCreate(
            ['email' => 'sales3@example.com'],
            [
                'name' => 'Sales Demo 3',
                'password' => Hash::make('Sales@123456'),
                'email_verified_at' => now(),
            ]
        );
        $sales3->syncRoles(['sales']);

        // ---------- Demo data ----------
        $this->seedForUser($sales, 6);
        $this->seedForUser($sales2, 4);
        $this->seedForUser($sales3, 4);

        // چند آیتم برای admin هم (نمایشی)
        $this->seedForUser($admin, 3);
    }

    private function seedForUser(User $user, int $count = 5): void
    {
        $ownerId = $user->id;

        // Customers
        $customers = collect();
        for ($i = 1; $i <= $count; $i++) {
            $email = "customer{$i}.{$user->id}@demo-crm.test";

            $customers->push(
                Customer::create([
                    'name' => "Customer {$i} ({$user->name})",
                    'email' => $email,
                    'phone' => '+98' . rand(9100000000, 9399999999),
                    'notes' => 'Demo customer created by seeder.',
                    'owner_id' => $ownerId,
                ])
            );
        }

        // Leads
        $leads = collect();
        $leadStatuses = ['new', 'contacted', 'qualified', 'lost'];

        for ($i = 1; $i <= $count; $i++) {
            $leadEmail = "lead{$i}.{$user->id}@demo-crm.test";

            $leads->push(
                Lead::create([
                    'name' => "Lead {$i} ({$user->name})",
                    'email' => $leadEmail,
                    'phone' => '+98' . rand(9100000000, 9399999999),
                    'source' => collect(['LinkedIn', 'Website', 'Referral', 'Cold Email'])->random(),
                    'status' => $leadStatuses[array_rand($leadStatuses)],
                    'owner_id' => $ownerId,
                ])
            );
        }

        // Tasks (طبق migration شما: notes دارد، description ندارد)
        $taskStatuses = ['open', 'done', 'canceled'];
        $taskTypes = ['call', 'email', 'meeting', 'follow_up'];

        for ($i = 1; $i <= $count * 2; $i++) {
            $attachToCustomer = ($i % 2 === 0);

            $customerId = null;
            $leadId = null;

            if ($attachToCustomer) {
                $customerId = $customers->random()->id;
            } else {
                $leadId = $leads->random()->id;
            }

            Task::create([
                'title' => "Task {$i} for {$user->name}",
                'notes' => 'Demo task generated by seeder.',
                'type' => $taskTypes[array_rand($taskTypes)],
                'status' => $taskStatuses[array_rand($taskStatuses)],
                'due_at' => now()->addDays(rand(1, 14)),
                'assigned_to' => $user->id,
                'customer_id' => $customerId,
                'lead_id' => $leadId,
            ]);
        }
    }
}
